# Generated by Django 4.1.7 on 2024-05-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('TypeID', models.AutoField(primary_key=True, serialize=False)),
                ('TypeName', models.CharField(max_length=255)),
            ],
        ),
    ]
