# Generated by Django 4.1.7 on 2024-05-28 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Image', models.CharField(max_length=255)),
                ('Rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('Sold', models.IntegerField()),
                ('Describe', models.TextField()),
                ('Discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('TypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.producttype')),
            ],
        ),
    ]
